import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SessionProviderWrapper from '@/components/SessionProviderWrapper';
import { TRPCProvider } from '@/trpc/client';
import { Toaster } from '@/components/ui/sonner';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import { Suspense } from 'react';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from './api/uploadthing/core';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* experimental shenanigans */}
        <Suspense fallback={<div>Loading...</div>}>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        </Suspense>
        <TRPCProvider>
          <Toaster />
          <SessionProviderWrapper>{children}</SessionProviderWrapper>
          <ReactQueryDevtools initialIsOpen={false} />
        </TRPCProvider>
      </body>
    </html>
  );
}
